### ISSUE TITLE
Reconsider Google as a source

### ISSUE THREAD

**Issue by bragefuglseth** [ideveCore/Valuta#25]
The Google provider falls short in many ways, and often leaves the app hanging. Given that the data is retrieved in a pretty hacky way, maybe it should be considered removed from the app altogether? ECB seems like a trustworthy and stable alternative, and other providers could always be added.

**Comment by ideveCore** [comment]
I was inclined to remove it, but not now. However, if it's truly necessary, I will remove it.

**Comment by ideveCore** [comment]
Hello, there are currently users who use the app and convert currencies that ECB does not support. I know that the Google provider is being used in a hacked way, but removing it now without prior notice to the users would render the app useless for some users currently.

**Comment by bragefuglseth** [comment]
If the additional currencies it provides are worth the instability, maybe keeping it as an option while marking it as unstable would be a sufficient compromise?

**Comment by bragefuglseth** [comment]
Also, I've found that when the app first hangs, it needs to be restarted to perform more conversions. Is it possible to make the app recover more gracefully from those situations?

**Comment by ideveCore** [comment]
Hello, I believe this has already been resolved. I will be closing this issue.
