### ISSUE TITLE
Unique name

### ISSUE THREAD

**Issue by bragefuglseth** [ideveCore/Valuta#31]
The current name is very generic, and the app can easily get lost among other similar ones. It would benefit from a more unique name. Some suggestions:

- Banknotes
- Inflation
- Greenback
- Pennies
- Transactions

**Comment by ideveCore** [comment]
I've noticed that I'm not good with icons and names 😅 ; I'll make these changes soon.

**Comment by Tuba2** [comment]
If I may, I believe I have a name suggestion that fits GNOME HIG perfectly _and_ describes precisely and succinctly what the app does:
- Valuta

According to [Merriam-Webster](https://www.merriam-webster.com/dictionary/valuta), _valuta_ means (in multiple languages) "the agreed upon or exchange value of a currency".

Also it has a nice ring to it :)

I think it might be a good option.

**Comment by ideveCore** [comment]
For me it's a great name, @bragefuglseth  fits the rules of Gnome Hig? If yes then this will be the name of the app thank you very much @Tuba2

**Comment by bragefuglseth** [comment]
Remember that you can get help with that, as mentioned in #32 😀

**Comment by ideveCore** [comment]
> Remember that you can get help with that, as mentioned in #32 😀

Yes well remembered, this time I will look for help, but for now I don't have time to make these changes.

**Comment by Tuba2** [comment]
> For me it's a great name, @bragefuglseth  fits the rules of Gnome Hig? If yes then this will be the name of the app thank you very much @Tuba2 

It does fit the GNOME HIG!

And I'm glad to help! I use your app very frequently, so I'm also thankful for your work! ;)
