### ISSUE TITLE
Unique icon

### ISSUE THREAD

**Issue by bragefuglseth** [ideveCore/Valuta#32]
The current app icon is partially derived from the example in the app icon guidelines. It would be fun if it could have an icon that is entirely its own! You can open a request in the [App Icon Requests](https://gitlab.gnome.org/teams/Design/app-icon-requests) repository when #31 has been resolved.

**Comment by Tuba2** [comment]
I posted a sketch on the [app icon request for Valuta](https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues/46).

If possible, do check it out and see if it makes sense to you 😃

**Comment by ideveCore** [comment]
> I posted a sketch on the [app icon request for Valuta](https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues/46).
> 
> If possible, do check it out and see if it makes sense to you 😃 

Hello, I just checked it out, the icon looks really good, but as I mentioned before, I have a lot of difficulty with design, even to evaluate 🤣, so I'll analyze it little by little, but I liked it, thank you for contributing so much to the app.

**Comment by ideveCore** [comment]
Hello @bragefuglseth , with all the difficulty 😅 I managed to make a small sketch of the new icon, of course, following the ideas they gave me in the [app icon request for Valuta](https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues/46).

**Comment by ideveCore** [comment]
> Hello @bragefuglseth , with all the difficulty 😅 I managed to make a small sketch of the new icon, of course, following the ideas they gave me in the [app icon request for Valuta](https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues/46).

As I mentioned, choosing a name and icon for the application, even though it may seem like an easier task, is very difficult for me.

**Comment by ideveCore** [comment]
Hello, I believe this has already been resolved. I will be closing this issue.
