### ISSUE TITLE
Bug: Error when getting currencies

### ISSUE THREAD

**Issue by CodeShakingSheep** [ideveCore/Valuta#33]
Possibly happening because of an API timeout?

![image](https://github.com/ideveCore/currency-converter/assets/19874562/eaaa8c26-1758-49c8-9ff8-1be4e9a5b588)

**Comment by ideveCore** [comment]
Hello, it is an error that occurs with the Google provider (Actually we use webscraping to fetch the data) In the new version of the application we added another provider (ECB)

**Comment by ideveCore** [comment]
We are undergoing an analysis to enter the GNOME circle, for now unfortunately I cannot release an update.

**Comment by CodeShakingSheep** [comment]
Hi, thanks for the info. I just wanted to report that today suddenly it just worked :smile: Thanks for this app.
![image](https://github.com/ideveCore/currency-converter/assets/19874562/25329f04-bbee-433f-b99f-cc5fa73ee211)

**Comment by CodeShakingSheep** [comment]
The bug happens again.

**Comment by ideveCore** [comment]
The bug occurs because the Google provider has an instability, but this has already been resolved in the new version. Please wait a little longer until I release it.

**Comment by ideveCore** [comment]
Hello, how are you? I hope you are doing well. The app update has been released. If you encounter any issues with the app update from the app store, try running the command `sudo flatpak update --app io.github.idevecore.CurrencyConverter`. After running it, confirm everything and you're done.

**Comment by ideveCore** [comment]
I will close this issue because two more providers have been added in addition to Google. However, if you encounter any errors, please do not hesitate to report them, as this makes the app even more robust and reliable.
