### ISSUE TITLE
org.gnome.Platform branch 44 end-of-life Info

### ISSUE THREAD

**Issue by alfonsocv12** [ideveCore/Valuta#39]
Hello, I got this info message on my last Flatpak update.

Do you need any help solving this issue 

![image](https://github.com/ideveCore/Valuta/assets/31135704/7ae34914-948f-4e5f-a1dd-a86a6c7b3f78)

**Comment by ideveCore** [comment]
Hello, the warning occurs because in this version, the application uses Gnome's runtime 44, while currently Gnome is already on runtime 46. I believe I will release a new version of the application with runtime 46 very soon, but this may take a few more months.

**Comment by ideveCore** [comment]
Hello, how are you? I hope you are doing well. The app update has been released. If you encounter any issues with the app update from the app store, try running the command `sudo flatpak update --app io.github.idevecore.CurrencyConverter`. After running it, confirm everything and you're done.

**Comment by alfonsocv12** [comment]
Hello @ideveCore I updated the app and everything its working fine thank you
