### ISSUE TITLE
Flathub - App not found

### ISSUE THREAD

**Issue by CodeShakingSheep** [ideveCore/Valuta#40]
![image](https://github.com/ideveCore/Valuta/assets/19874562/f4fdcfac-4b83-4a33-bebc-5d6afc61cba5)

**Comment by ideveCore** [comment]
The application has changed its name, but an update for Flathub has not yet been made.

**Comment by ideveCore** [comment]
The application will only be updated once this process is completed. Follow the progress at https://gitlab.gnome.org/Teams/Circle/-/issues/197
