### ISSUE TITLE
Metainfo screenshots do not use Cantarell

### ISSUE THREAD

**Issue by bragefuglseth** [ideveCore/Valuta#41]
I don't know what font it is, but it's not Cantarell, at least :slightly_smiling_face:

**Comment by ideveCore** [comment]
Wow, I hadn't noticed that, the default font of my system is Noto Sans, I forgot to make the switch before taking the screenshots.

**Comment by ideveCore** [comment]
I will redo the screenshots as soon as possible.

**Comment by ideveCore** [comment]
I just switched the screenshots, and I noticed that the app had new translations, so I decided to release an update.

**Comment by bragefuglseth** [comment]
Great!
