### ISSUE TITLE
Error receiving the flatpack Instance for debug_info

### ISSUE THREAD

**Issue by Rirusha** [ideveCore/Valuta#43]
https://github.com/ideveCore/Valuta/blob/b67655537dcb92478a03b0dc7ad1464b2a766ff5/src/about.py#L31

In native builds, an error appears on this line. Do you mind if I send a PR with the condition processing if the file does not exist?
I am creating a issue because some project maintainers are radically opposed to non-flatpack builds.

**Comment by ideveCore** [comment]
Hi, thanks for the contribution, I'll check the pull request soon.

**Comment by City-busz** [comment]
I created a pull request that fixes this problem: https://github.com/ideveCore/Valuta/pull/45
